apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: changeme
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/cb-kubecd/qcon-demo-test:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    artifacts:
    - docker: {}
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/cb-kubecd/qcon-demo-test:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: qcon-demo-test
        chartPath: charts/qcon-demo-test
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/cb-kubecd/qcon-demo-test'
          image.tag: '{{.DIGEST_HEX}}'
